### ISSUE TITLE
Adding Punctuation?

### ISSUE THREAD

**Issue by JudeAsterix** [EnriqueGambra/Morse-Code-Encrypter-Decypter#1]
I do like the program overall, but I noticed that punctuation doesn't get converted to Morse code. For instance, the following text is inserted
`SOS!`
And the Morse Code is output
`...---...!`
I think you should add that to make it more complete. For the sake of convenience, I added a table for punctuation symbols and their Morse code translations.

| Symbol | Morse Code | Notes |
| :---: | :---: | :---: |
| Period [.] | .-.-.- | |
| Comma [,] | --..-- | |
| Question Mark [?] | ..--.. | |
| Apostrophe ['] | .----. | |
| Exclamation Point [!] | -.-.-- | Symbol not recommended by the ITU |
| Slash [/] | -..-. | |
| Open Parenthesis [(] | -.--. | |
| Closed Parenthesis [)] | -.--.- | |
| Ampersand [&] | .-... | Prosign for 'WAIT'|
| Colon [:] | ---... | |
| Semicolon [;] | -.-.-. | |
| Double Dash [=] | -...- | |
| Plus Sign [+] | .-.-. | |
| Hyphen [-] | -....- | |
| Underscore [_] | ..--.- | Not in the ITU-R |
| Quotation Mark ["] | .-..-. | |
| Dollar Sign [$] | ...-..- | Not in the ITU-R |
| At Sign [@] | .--.-. | Not in the ITU-R |

I'm not sure whether or not you want to make it accurate or not, but I think that it will be a fun addition at the very least. :)

**Comment by EnriqueGambra** [comment]
Hi Jude!!! Long time no see!

I will add this for sure, I didn't even think of it. Haha always looking through my code. Thanks so much, I hope all is well and your classes are fun. I'll add this right now and push it to master.

Thanks!!!!
